### ISSUE TITLE
Bot won't work

### ISSUE THREAD

**Issue by denkorzh** [just806me/voiceru_bot#3]
Now bot asks for Yandex Speechkit Cloud key for every usage. But even after setting it with `/key` command it says the key is not valid and refuses to produce voice messages

**Comment by just806me** [comment]
Yes, now bot only supports Yandex voices as Ivona TTS in no longer available.

If bot says a key is not valid, it's likely that it is so. Yandex key should be a valid uuid v4, so bot checks it via a regex `^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`. This check was added in d461063. Isn't it right?
